### ISSUE TITLE
Education of proper recycling techniques

### ISSUE THREAD

**Issue by thomasstoelen** [climatepatch/formation#24]
Inspired by: #1 
> IDEA: Use data collected to provide consumers with examples of non-environment conscious products and their alternatives.

A variety of educational material including:
- Life hacks and household tips of reusing common goods for another purpose. 
- How to take care of waste chemicals or other dangerous depleted goods.
- Solutions for taking alternative measures. (e.g bringing your own bag to the supermarket)

Delivery to the end user:
- Web app or website
- Search a particular product or depleted waste and find the appropriate recycling method.
  - Perhaps incentives for business' to attract consumers to engage recycling with them?
  - E.g. Electronics stores advertising their battery recycling
- Promote ways to reuse items through infographics
- Promote solutions to take alternative measures through infographics

**Comment by VictorPeralta** [comment]
I think this is a great idea, recycling is one of the easiest things everyone can do to have a positive impact on the environment.
